### ISSUE TITLE
Webp images show colourless

### ISSUE THREAD

**Issue by AreebKhan17** [MagestyApps/module-web-images#10]
I have installed your extension, when I add .**webp** image in product images it works nice. At the PDP when you swipe and open webp picture it is not showing properly. It is colourless sometimes and some webp images are blur. Please share your thought about that. Is that an extension issue? or magento issue or what? 
Waiting for the reply..

**Comment by nayembwip** [comment]
<img width="807" alt="Screenshot 2022-08-19 at 7 01 55 PM" src="https://user-images.githubusercontent.com/73821752/185624069-06b4367d-4ff3-4c92-a19a-59bb70fcb40f.png">
Same thing happening with me also.

**Comment by nayembwip** [comment]
@MagestyApps could you look at this

**Comment by nmarquev** [comment]
Hi, same issue here

**Comment by ppeyman** [comment]
same us

**Comment by ppeyman** [comment]
> Hi, same issue here
> 
> original webp ![image](https://user-images.githubusercontent.com/20818155/197447729-6b925865-0bdd-4bc8-b7cc-a2c25c7d1fb6.png)
> 
> after uploaded ![image](https://user-images.githubusercontent.com/20818155/197447757-5005237e-151f-489b-aa04-0a43e492b873.png)

same us !!

**Comment by maquowicz** [comment]
Anybody figured this out ? Same issue here, 2.4.5-p1, php8.1. 
Looks like happens only to bigger images when resizing kicks in.

**Comment by leatonvof** [comment]
> Anybody figured this out ? Same issue here, 2.4.5-p1, php8.1. Looks like happens only to bigger webp images when resizing kicks in.

Sadly having the same issue here

**Comment by gino2014** [comment]
Same issue still with 1.1.7 and 2.4.3-p3 and PHP 7.4.x

**Comment by maquowicz** [comment]
Make sure you have it in your env and try ImageMagick as image processor. Stores > Cfg > Advanced > Developer > Image Processing Settings. 
![Screenshot from 2023-02-15 11-02-06](https://user-images.githubusercontent.com/10026557/218996908-6ce6ebe9-896f-4f84-9a24-48905eb83938.png)

**Comment by gino2014** [comment]
Hello @maquowicz , 

with ImageMagick it seems now to work. Thanks for your help. Maybe you could add this information to your instruction. 
Kind regards
Gino

**Comment by ravikumar-fledgedigital** [comment]
Hi, has Anybody figured this out? Same issue here in Magento 2.4.6, php8.2.

**Comment by ravikumar-fledgedigital** [comment]
> Make sure you have it in your env and try ImageMagick as image processor. Stores > Cfg > Advanced > Developer > Image Processing Settings. ![Screenshot from 2023-02-15 11-02-06](https://user-images.githubusercontent.com/10026557/218996908-6ce6ebe9-896f-4f84-9a24-48905eb83938.png)

It is not working.

**Comment by gino2014** [comment]
We can confirm that it is working with magento 2.4.3 and 2.4.5 with PHP 7.4x. - PHP 8.1 and 8.2 we still did not used until now.

**Comment by MagestyApps** [comment]
We've just released version 1.1.8 where this issue is fixed. Please, upgrade to the latest version.
