### ISSUE TITLE
Compile Issues coming

### ISSUE THREAD

**Issue by shanu6thstreet** [MagestyApps/module-web-images#12]
Source class "\MagestyApps\WebImages\Model\AssetInterface" for "MagestyApps\WebImages\Model\AssetInterfaceFactory" generation does not exist.

**Comment by MagestyApps** [comment]
@shanu6thstreet Hi. Could you please clarify which Magento version you're using? Probably, this is a version compatibility issue. Because we can't reproduce the issue with M2.4.3.

**Comment by shanu6thstreet** [comment]
@MagestyApps  Magento 2.3.1 version this issues coming

**Comment by vandark25** [comment]
On 2.3.7 Class Magento\Framework\Filesystem\Directory\TargetDirectory does not exist

**Comment by sterlinux** [comment]
Someone resolved this issue? Magento 2.3.7
TKS.

**Comment by MagestyApps** [comment]
Unfortunately, the module is compatible with Magento version 2.4 or newer. Since later Magento versions are no longer maintained by Adobe, it doesn't make sense to fix the compatibility for our module as well.
