### ISSUE TITLE
Include PDFs?

### ISSUE THREAD

**Issue by lfolco** [MagestyApps/module-web-images#15]
Would it be possible to update this module to include PDFs? They are not images, but would be very useful.

**Comment by xnhinzkyx** [comment]
Yeah I agree. It would be very useful.

**Comment by MagestyApps** [comment]
Hi @lfolco @xnhinzkyx ,

Unfortunately, this is out of the scope of this module. It works with images only. There workaround for PDF files should be completely different. Thanks for the idea, we will think about creating a separate module to support PDF files. But in terms of this module, this feature won't be added. Sorry.
