### ISSUE TITLE
with watermark doesn't show

### ISSUE THREAD

**Issue by ppeyman** [MagestyApps/module-web-images#16]
hi 
I Installed extension if you have watermark for base image doesn't show image and show magento thumbnail 
i tested it with magento 2.4.5

**Comment by MagestyApps** [comment]
Hi @ppeyman 

Unfortunately, this feature is not possible at the moment. The PHP image libraries that are currently used in Magento cannot edit SVG images. As a result, it is not possible to add a watermark to an SVG image or to add an SVG watermark.
