### ISSUE TITLE
Fix for Type Error occurred when creating object: Magento\MediaStorage\Model\File\Validator\NotProtectedExtension\Interceptor, array_keys(): Argument #1 ($array) must be of type array, string given [] []

### ISSUE THREAD

**Issue by maquowicz** [MagestyApps/module-web-images#18]
Hey

Nice work! Thanks for sharing!

Found that module doesn't work in M2.4.5 running php8.1

in vendor/magestyapps/module-web-images/Plugin/File/Validator/NotProtectedExtensionPlugin.php 
around line 40 before foreach loop add: 

`$result = is_string($result) ? explode(",", $result) : $result;`

**Comment by MagestyApps** [comment]
Hi @maquowicz 

Thanks for the detailed report of the issue. With your help, we fixed the issue and released it in version 1.1.7.
