### ISSUE TITLE
Existing SVG/WEBP images do not sync with commands

### ISSUE THREAD

**Issue by addMitt** [MagestyApps/module-web-images#21]
I already had a folder with a lot of .svg's in it, and the following commands did not pull them in to the media gallery, like they did for the default file types:

```
bin/magento media-content:sync
bin/magento media-gallery:sync
```

I was able to fix this by adding the following to the di.xml in `MagestyApps/WebImages/etc/di.xml`

```xml
    <type name="Magento\MediaGallerySynchronization\Model\FetchMediaStorageFileBatches">
        <arguments>
            <argument name="fileExtensions" xsi:type="array">
                <item name="svg" xsi:type="string">svg</item>
                <item name="webp" xsi:type="string">webp</item>
            </argument>
        </arguments>
    </type>
```

**Comment by MagestyApps** [comment]
@addMitt thanks for tracking and fixing the issue. We've included your fix in version 1.1.8.
