### ISSUE TITLE
File validation failed - Uploading SVG file

### ISSUE THREAD

**Issue by atty31** [MagestyApps/module-web-images#3]
I m getting this error message `File validation failed ` when I tried to upload a svg file to a static block.
I m running Magento 2.4.2 and the module version is 1.0.1
Could you please have a look ? Thanks

**Comment by MagestyApps** [comment]
Hi,

We investigated the issue and found that some of the SVG images have MIME type 'image/svg' and some of them - 'image/svg+xml'. Probably, the image you're trying to upload has the second type. And this type was not supported by the extension. But we solved the issue and updated the extension. Please, upgrade to the latest version 1.0.2.

Please, try it and in case you are still having the issue, please send us the file which you cannot upload. Thanks.

**Comment by lakshmana** [comment]
hi there, we still have this issue on our magento 2.4.4 hosted on nginx server. Its ok on apache server btw. Can you please check this on nginx ?
