### ISSUE TITLE
SVG not visible in media gallery

### ISSUE THREAD

**Issue by boo-code** [MagestyApps/module-web-images#4]
In Magento ver. 2.4.2-p1 SVG files are not visible in the gallery.

![image](https://user-images.githubusercontent.com/65190196/119466145-a21a7200-bd44-11eb-87fb-992cca516966.png)

![image](https://user-images.githubusercontent.com/65190196/119466223-b3637e80-bd44-11eb-8165-3d7e2b2f0bf0.png)

**Comment by boo-code** [comment]
The issue appears when in the Advanced->System configuration the old media gallery is set to "no".

![image](https://user-images.githubusercontent.com/65190196/119467266-a5622d80-bd45-11eb-9dca-74bfeba5f173.png)

**Comment by MagestyApps** [comment]
Hi,

We haven't tested the module under M2.4.2-p1 yet. Will do our best to debug and fix the issue in the nearest few days.

**Comment by boo-code** [comment]
P1 is just security, bug and performance fixes. In this case, 2.4.2 should be the same. The problem is in the old and new media gallery.
The old gallery works well, but not a new one.

**Comment by MagestyApps** [comment]
Ok, we fixed the compatibility issue when new media gallery is enabled. Please download the updated version 1.0.3.
